# Generated by Django 5.0.2 on 2025-02-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
